# -*- coding: utf-8 -*-
"""nlp_hw1_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1omUevLv7n_vYz48JYkBfnBr-3xinLJxF

## Part I: Data Pre-processing
"""

import pandas as pd

# Download the Google Analogy dataset
#!wget http://download.tensorflow.org/data/questions-words.txt

# Preprocess the dataset
file_name = "questions-words"
with open(f"{file_name}.txt", "r") as f:
    data = f.read().splitlines()

# check data from the first 10 entries
for entry in data[:10]:
    print(entry)

# TODO1: Write your code here for processing data to pd.DataFrame
# Please note that the first five mentions of ": " indicate `semantic`,
# and the remaining nine belong to the `syntatic` category.

questions = []
categories = []
sub_categories = []
semantic_count = 0

for string in data:
    if semantic_count < 6:
        if string.startswith(":"):
            semantic_count += 1
            current_category = string
        else:
            questions.append(string)
            categories.append("Semantic")
            sub_categories.append(current_category)

    else:
        if string.startswith(":"):
            current_category = string
        else:
            questions.append(string)
            categories.append("Syntatic")
            sub_categories.append(current_category)

# Create the dataframe
df = pd.DataFrame(
    {
        "Question": questions,
        "Category": categories,
        "SubCategory": sub_categories,
    }
)

df.head()

df.to_csv(f"{file_name}.csv", index=False)

"""## Part II: Use pre-trained word embeddings
- After finish Part I, you can run Part II code blocks only.
"""

import pandas as pd
import numpy as np
import gensim.downloader
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

data = pd.read_csv("questions-words.csv")

MODEL_NAME = "glove-wiki-gigaword-100"
# You can try other models.
# https://radimrehurek.com/gensim/models/word2vec.html#pretrained-models

# Load the pre-trained model (using GloVe vectors here)
model = gensim.downloader.load(MODEL_NAME)
print("The Gensim model loaded successfully!")

# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

for analogy in tqdm(data["Question"]):
    # TODO2: Write your code here to use pre-trained word embeddings for getting predictions of the analogy task.
    # You should also preserve the gold answers during iterations for evaluations later.
    """Hints
    # Unpack the analogy (e.g., "man", "woman", "king", "queen")
    # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
    # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L776
    # Mikolov et al., 2013: big - biggest and small - smallest
    # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
    """

    word_a, word_b, word_c, word_d = analogy.split()
    golds.append(word_d)

    try:
        res_seq = model.most_similar(
            positive=[word_b, word_c], negative=[word_a], topn=1
        )
        # using the provided source
        # return a sequence of (key, similarity)

        pred = res_seq[0][0]
        preds.append(pred)

    except:
        preds.append(None)

# Perform evaluations. You do not need to modify this block!!


def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)


golds_np, preds_np = np.array(golds), np.array(preds)
data = pd.read_csv("questions-words.csv")

# Evaluation: categories
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

# Evaluation: sub-categories
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category{sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# TODO3: Plot t-SNE for the words in the SUB_CATEGORY `: family`

family_words = []
family_vectors = []

for analogy, subcategory in zip(data["Question"], data["SubCategory"]):
    if subcategory == SUB_CATEGORY:
        words = analogy.split()

        for word in words:
            if word in model.key_to_index and word not in family_words:
                family_words.append(word)
                family_vectors.append(model[word])

family_vectors = np.array(family_vectors)

tsne = TSNE(
    n_components=2, perplexity=min(30, len(family_vectors) - 1), random_state=42
)
vectors_2d = tsne.fit_transform(family_vectors)

plt.figure(figsize=(12, 8))
scatter = plt.scatter(vectors_2d[:, 0], vectors_2d[:, 1], s=100, alpha=0.7, c="blue")
for i, word in enumerate(family_words):
    plt.annotate(
        word,
        xy=(vectors_2d[i, 0], vectors_2d[i, 1]),
        xytext=(5, 2),
        textcoords="offset points",
        fontsize=10,
        ha="left",
    )

plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.title("Word Relationships from Google Analogy Task")
plt.show()
plt.savefig("word_relationships.png", bbox_inches="tight")

"""### Part III: Train your own word embeddings

### Get the latest English Wikipedia articles and do sampling.
- Usually, we start from Wikipedia dump (https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2). However, the downloading step will take very long. Also, the cleaning step for the Wikipedia corpus ([`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus)) will take much time. Therefore, we provide cleaned files for you.
"""

# Download the split Wikipedia files
# Each file contain 562365 lines (articles).
#!gdown --id 1jiu9E1NalT2Y8EIuWNa1xf2Tw1f1XuGd -O wiki_texts_part_0.txt.gz
#!gdown --id 1ABblLRd9HXdXvaNv8H9fFq984bhnowoG -O wiki_texts_part_1.txt.gz
#!gdown --id 1z2VFNhpPvCejTP5zyejzKj5YjI_Bn42M -O wiki_texts_part_2.txt.gz
#!gdown --id 1VKjded9BxADRhIoCzXy_W8uzVOTWIf0g -O wiki_texts_part_3.txt.gz
#!gdown --id 16mBeG26m9LzHXdPe8UrijUIc6sHxhknz -O wiki_texts_part_4.txt.gz

# Download the split Wikipedia files
# Each file contain 562365 lines (articles), except the last file.
#!gdown --id 17JFvxOH-kc-VmvGkhG7p3iSZSpsWdgJI -O wiki_texts_part_5.txt.gz
#!gdown --id 19IvB2vOJRGlrYulnTXlZECR8zT5v550P -O wiki_texts_part_6.txt.gz
#!gdown --id 1sjwO8A2SDOKruv6-8NEq7pEIuQ50ygVV -O wiki_texts_part_7.txt.gz
#!gdown --id 1s7xKWJmyk98Jbq6Fi1scrHy7fr_ellUX -O wiki_texts_part_8.txt.gz
#!gdown --id 17eQXcrvY1cfpKelLbP2BhQKrljnFNykr -O wiki_texts_part_9.txt.gz
#!gdown --id 1J5TAN6bNBiSgTIYiPwzmABvGhAF58h62 -O wiki_texts_part_10.txt.gz

# Extract the downloaded wiki_texts_parts files.
#!gunzip -k wiki_texts_part_*.gz

# Combine the extracted wiki_texts_parts files.
#!cat wiki_texts_part_*.txt > wiki_texts_combined.txt

# Check the first ten lines of the combined file
#!head -n 10 wiki_texts_combined.txt

"""Please note that we used the default parameters of [`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus) for cleaning the Wiki raw file. Thus, words with one character were discarded."""

# Now you need to do sampling because the corpus is too big.
# You can further perform analysis with a greater sampling ratio.

import random

wiki_txt_path = "wiki_texts_combined.txt"
# wiki_texts_combined.txt is a text file separated by linebreaks (\n).
# Each row in wiki_texts_combined.txt indicates a Wikipedia article.

output_path = "wiki_texts_sampled.txt"  # add this
with open(wiki_txt_path, "r", encoding="utf-8") as f:
    with open(output_path, "w", encoding="utf-8") as output_file:
        # TODO4: Sample `20%` Wikipedia articles
        # Write your code here

        # all_lines = f.readlines() # this will fxxk the ram
        sample_ratio = 0.2
        total_lines = sum(1 for _ in f)
        sample_size = int(total_lines * sample_ratio)

        f.seek(0)
        selected_lines = set(random.sample(range(total_lines), sample_size))
        for line_num, line in enumerate(f):
            if line_num in selected_lines:
                output_file.write(line)

# TODO5: Train your own word embeddings with the sampled articles
# https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec
# Hint: You should perform some pre-processing before training.

import nltk
import logging
import multiprocessing
from gensim.models import Word2Vec
from gensim.parsing.preprocessing import remove_stopwords
from gensim.utils import simple_preprocess

nltk.download("punkt_tab")
logging.basicConfig(
    format="%(asctime)s : %(levelname)s : %(message)s", level=logging.INFO
)


class PreProcess:
    def __init__(self, filename):
        self.filename = filename
        print(f"Loading data from: {filename}\n")

    def __iter__(self):
        with open(self.filename, "r", encoding="utf-8") as f:
            for line_num, line in enumerate(f):
                line = line.strip()
                if line:
                    sentences = self.sent_preproc(line)
                    for sentence in sentences:
                        if len(sentence) >= 3:
                            yield sentence

                if line_num % 100000 == 0:
                    print(f"Processed {line_num} articles")

    def sent_preproc(self, text):
        raw_sentences = nltk.sent_tokenize(text)
        processed_sentences = []

        for sentence in raw_sentences:
            sentence = sentence.strip()
            if not sentence:
                continue

            sentence = sentence.lower()
            sentence = remove_stopwords(sentence)
            tokens = simple_preprocess(sentence, min_len=3, max_len=15)

            if tokens:
                processed_sentences.append(tokens)

        return processed_sentences


sentences = PreProcess(f"wiki_texts_sampled.txt")

my_model = Word2Vec(
    sentences=sentences,
    vector_size=300,
    window=8,
    min_count=5,
    workers=multiprocessing.cpu_count(),
    sg=1,
    epochs=15,
    negative=10,
    compute_loss=False,
)

model_filename = f"word2vec.model"
my_model.save(model_filename)
print(f"Model saved as: {model_filename}")
print(f"\n Training completed!\n\n")

data = pd.read_csv("questions-words.csv")

# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

for analogy in tqdm(data["Question"]):
    # TODO6: Write your code here to use your trained word embeddings for getting predictions of the analogy task.
    # You should also preserve the gold answers during iterations for evaluations later.
    """Hints
    # Unpack the analogy (e.g., "man", "woman", "king", "queen")
    # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
    # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L776
    # Mikolov et al., 2013: big - biggest and small - smallest
    # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
    """
    word_a, word_b, word_c, word_d = analogy.split()
    golds.append(word_d)

    try:
        res_seq = my_model.wv.most_similar(
            positive=[word_b, word_c], negative=[word_a], topn=1
        )
        pred = res_seq[0][0]
        preds.append(pred)

    except:
        preds.append(None)


def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)


golds_np, preds_np = np.array(golds), np.array(preds)

for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category{sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# TODO7: Plot t-SNE for the words in the SUB_CATEGORY `: family`

family_words = []
family_vectors = []
for analogy, subcategory in zip(data["Question"], data["SubCategory"]):
    if subcategory == SUB_CATEGORY:
        words = analogy.split()

        for word in words:
            if word in my_model.wv.key_to_index and word not in family_words:
                family_words.append(word)
                family_vectors.append(my_model.wv[word])

family_vectors = np.array(family_vectors)

tsne = TSNE(
    n_components=2, perplexity=min(30, len(family_vectors) - 1), random_state=42
)
vectors_2d = tsne.fit_transform(family_vectors)

plt.figure(figsize=(12, 8))
scatter = plt.scatter(vectors_2d[:, 0], vectors_2d[:, 1], s=100, alpha=0.7, c="blue")
for i, word in enumerate(family_words):
    plt.annotate(
        word,
        xy=(vectors_2d[i, 0], vectors_2d[i, 1]),
        xytext=(5, 2),
        textcoords="offset points",
        fontsize=10,
        ha="left",
    )

plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.title("Word Relationships from Google Analogy Task")
plt.show()
plt.savefig("word_relationships.png", bbox_inches="tight")
